import { mockDrivers, mockRecommendations, mockAlerts, mockBriefing } from './mockData';

// ops backend (port 8000) — handles drivers, loads, dispatch scoring
const OPS_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';
// AI backend (port 5001) — handles chat via Groq + LangChain
const AI_URL = import.meta.env.VITE_AI_URL || 'http://localhost:5001';

async function apiFetch(url, options = {}) {
  try {
    const res = await fetch(url, {
      headers: { 'Content-Type': 'application/json', ...options.headers },
      ...options,
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return await res.json();
  } catch (err) {
    console.warn(`[api] fetch failed for ${url}:`, err.message);
    return null;
  }
}

export const fleetService = {
  getDrivers: async () => {
    const data = await apiFetch(`${OPS_URL}/driver-cards`);
    if (data && Array.isArray(data.drivers)) return data.drivers;
    // Fallback to mock if backend unreachable
    console.warn('[fleetService] falling back to mock drivers');
    return mockDrivers;
  },
};

export const dispatchService = {
  getRecommendations: async (loadId = 'LD-4821') => {
    const data = await apiFetch(`${OPS_URL}/loads/${loadId}/recommendations`);
    if (data && Array.isArray(data.recommendations)) return data.recommendations;
    console.warn('[dispatchService] falling back to mock recommendations');
    return mockRecommendations;
  },
  getRecommendationsExplained: async (loadId) => {
    if (!loadId) return null;
    return fetchJson(`/loads/${loadId}/recommendation/explain`);
  },
  assignLoad: async (loadId, driverId) => {
    // POST to ops backend once that endpoint exists; graceful stub for now
    console.log(`[dispatchService] assigning load ${loadId} to driver ${driverId}`);
    return { success: true };
  },
  getLoads: async () => {
    return fetchJson('/loads');
  }
};

export const alertService = {
  getAlerts: async () => {
    // Alerts are derived from driver data — fetch driver-cards and extract alerts
    const data = await apiFetch(`${OPS_URL}/driver-cards`);
    if (data && Array.isArray(data.drivers)) {
      const alerts = [];
      data.drivers.forEach(driver => {
        (driver.alerts || []).forEach(alert => {
          alerts.push({
            id: `${driver.id}-${Math.random().toString(36).substr(2, 5)}`,
            driverId: driver.id,
            driverName: driver.name,
            severity: alert.severity || 'medium',
            message: alert.text || alert,
            timestamp: new Date().toISOString(),
          });
        });
      });
      if (alerts.length > 0) return alerts;
    }
    console.warn('[alertService] falling back to mock alerts');
    return mockAlerts;
  },
};

export const chatService = {
  // sendMessage routes to the Flask AI layer on port 5001
  sendMessage: async (message, history = []) => {
    const data = await apiFetch(`${AI_URL}/api/chat`, {
      method: 'POST',
      body: JSON.stringify({ question: message, history }),
    });
    if (data && !data.error) {
      return {
        id: Math.random().toString(36).substr(2, 9),
        role: 'assistant',
        content: data,          // full structured AI response
        timestamp: new Date().toISOString(),
      };
    }
    // Fallback
    console.warn('[chatService] falling back to stub response');
    return {
      id: Math.random().toString(36).substr(2, 9),
      role: 'assistant',
      content: `I've analyzed the current fleet metrics. Regarding "${message}" — please ensure the AI backend (port 5001) is running.`,
      timestamp: new Date().toISOString(),
    };
  },
};

export const briefingService = {
  getDailyBriefing: async () => {
    // Briefing is generated by the AI layer — future endpoint: GET /api/briefing
    const data = await apiFetch(`${AI_URL}/api/briefing`);
    if (data && !data.error) return data;
    console.warn('[briefingService] falling back to mock briefing');
    return mockBriefing;
  },
};